export type Screen = {
  id: string;
  name: string;
  group: string;
  states: string[];
  purpose: string;
};
export const supplierNames = [
  "Aster Consulting",
  "Tern Digital",
  "Ridgeline Advisory",
];
export const screens: Screen[] = [
  {
    id: "home",
    name: "Client home dashboard",
    group: "Overview",
    states: ["normal"],
    purpose:
      "Client starting point: understand Groundwork, review workspace activity and take the next step.",
  },
  {
    id: "guide",
    name: "Screen & state guide",
    group: "Overview",
    states: ["normal"],
    purpose: "Explore every screen and state in this prototype.",
  },
  {
    id: "watchlist",
    name: "Opportunity watchlist",
    group: "Opportunities",
    states: ["normal", "loading", "empty", "error", "stale"],
    purpose: "Find opportunities, filter by interest, inspect changes.",
  },
  {
    id: "pursuit",
    name: "Pursuit workspace",
    group: "Opportunities",
    states: [
      "normal",
      "loading",
      "processing",
      "partial",
      "complete",
      "reassessed",
      "conflict",
      "stale",
      "error",
    ],
    purpose:
      "Understand the competitive field, incumbent position and separate firm context.",
  },
  {
    id: "requirements",
    name: "All requirements",
    group: "Opportunities",
    states: ["normal", "loading", "empty", "partial", "complete", "conflict"],
    purpose: "Review mandatory conditions and focus an individual requirement.",
  },
  {
    id: "review",
    name: "Resolve requirement",
    group: "Opportunities",
    states: ["normal", "saving", "success", "error", "conflict"],
    purpose: "Attach evidence and record an attributed review.",
  },
  {
    id: "decisions",
    name: "Decision & history",
    group: "Opportunities",
    states: ["normal", "empty", "complete", "stale", "saving", "error"],
    purpose: "Record a deliberate decision and inspect the version used.",
  },
  {
    id: "sources",
    name: "Evidence library",
    group: "Evidence",
    states: ["normal", "loading", "empty", "partial", "error"],
    purpose: "See source origins, versions, access and coverage.",
  },
  {
    id: "document",
    name: "Source viewer",
    group: "Evidence",
    states: ["normal", "loading", "partial", "conflict", "unavailable"],
    purpose: "Read an exact source page, version and highlighted excerpt.",
  },
  {
    id: "upload",
    name: "Add documents",
    group: "Evidence",
    states: [
      "normal",
      "uploading",
      "processing",
      "partial",
      "complete",
      "error",
    ],
    purpose: "Add sample files and inspect individual file outcomes.",
  },
  {
    id: "request",
    name: "Request analysis",
    group: "Reports",
    states: ["normal", "loading", "empty", "submitting", "error"],
    purpose: "Choose scope and confirm the firm and included source versions.",
  },
  {
    id: "processing",
    name: "Analysis progress",
    group: "Reports",
    states: [
      "normal",
      "queued",
      "processing",
      "retrying",
      "review",
      "partial",
      "failed",
      "cancelled",
      "complete",
    ],
    purpose: "Follow a saved request and recover or cancel it.",
  },
  {
    id: "reports",
    name: "Report library",
    group: "Reports",
    states: ["normal", "loading", "empty", "processing", "error"],
    purpose: "Find accepted versions and work in progress.",
  },
  {
    id: "report",
    name: "Report reader",
    group: "Reports",
    states: [
      "normal",
      "loading",
      "partial",
      "stale",
      "unavailable",
      "reassessed",
    ],
    purpose: "Read a fixed report version and its evidence basis.",
  },
  {
    id: "sharing",
    name: "Share management",
    group: "Reports",
    states: ["normal", "empty", "saving", "error", "revoked", "expired"],
    purpose: "Preview, create and revoke a demo share of one report version.",
  },
  {
    id: "shared",
    name: "Recipient view",
    group: "Reports",
    states: ["normal", "loading", "expired", "revoked", "unavailable"],
    purpose: "See exactly what an external recipient can access.",
  },
  {
    id: "brief",
    name: "Weekly brief",
    group: "Reports",
    states: ["normal", "loading", "empty", "partial", "processing"],
    purpose:
      "Read a concise week of opportunities, changes and market signals.",
  },
  {
    id: "market",
    name: "Market intelligence",
    group: "Market",
    states: ["normal", "loading", "empty", "partial", "error"],
    purpose: "Explore evidence-backed market context and forthcoming work.",
  },
  {
    id: "agencies",
    name: "Agency directory",
    group: "Market",
    states: ["normal", "loading", "empty", "error"],
    purpose: "Find agencies and view their procurement context.",
  },
  {
    id: "agency",
    name: "Agency profile",
    group: "Market",
    states: ["normal", "loading", "partial", "stale", "error"],
    purpose: "Connect an agency’s notices, plans, awards and sources.",
  },
  {
    id: "competitors",
    name: "Competitor directory",
    group: "Market",
    states: ["normal", "loading", "empty", "error"],
    purpose: "Find suppliers and request a competitor assessment.",
  },
  {
    id: "competitor",
    name: "Competitor profile",
    group: "Market",
    states: ["normal", "loading", "processing", "partial", "error"],
    purpose: "Keep historical participation distinct from predicted bidding.",
  },
  {
    id: "awards",
    name: "Award history",
    group: "Market",
    states: ["normal", "loading", "empty", "partial", "error"],
    purpose:
      "Inspect contract values without duplicating category/region totals.",
  },
  {
    id: "signal",
    name: "Policy & plan signal",
    group: "Market",
    states: ["normal", "loading", "stale", "conflict", "unavailable"],
    purpose:
      "Read a source-backed planning signal without implying an open tender.",
  },
  {
    id: "renewals",
    name: "Renewal forecasts",
    group: "Market",
    states: ["normal", "loading", "empty", "partial", "error"],
    purpose: "Inspect inferred windows and the assumptions behind them.",
  },
  {
    id: "firm",
    name: "Firm profile",
    group: "Account",
    states: ["normal", "loading", "empty", "saving", "success", "error"],
    purpose: "Maintain the firm interests and private capability context.",
  },
  {
    id: "preferences",
    name: "Delivery preferences",
    group: "Account",
    states: ["normal", "loading", "saving", "success", "error"],
    purpose: "Choose which updates arrive and when.",
  },
  {
    id: "access",
    name: "Sign-in journey",
    group: "Account",
    states: ["normal", "submitting", "success", "error", "expired"],
    purpose: "Preview passwordless entry without real authentication or email.",
  },
  {
    id: "onboarding",
    name: "Firm setup",
    group: "Account",
    states: ["normal", "saving", "success", "error"],
    purpose: "Set initial interests before opening the watchlist.",
  },
  {
    id: "ops",
    name: "Operator work queue",
    group: "Operations",
    states: ["normal", "loading", "empty", "partial", "error"],
    purpose: "See pending, failed and successful workflows.",
  },
  {
    id: "run",
    name: "Run & stage detail",
    group: "Operations",
    states: [
      "normal",
      "loading",
      "queued",
      "processing",
      "retrying",
      "review",
      "failed",
      "cancelled",
      "complete",
    ],
    purpose: "Inspect stage dependencies, input versions and recovery.",
  },
  {
    id: "source-health",
    name: "Source health",
    group: "Operations",
    states: ["normal", "loading", "empty", "partial", "error"],
    purpose: "Inspect freshness and the last accepted publication.",
  },
  {
    id: "source-detail",
    name: "Source snapshots",
    group: "Operations",
    states: ["normal", "loading", "processing", "partial", "error"],
    purpose: "Compare source versions and inspect extraction coverage.",
  },
  {
    id: "schedules",
    name: "Workflow schedules",
    group: "Operations",
    states: ["normal", "loading", "paused", "error"],
    purpose: "Inspect all scheduled workflow families and dependency gates.",
  },
  {
    id: "usage",
    name: "Usage & costs",
    group: "Operations",
    states: ["normal", "loading", "empty", "partial", "error"],
    purpose: "Inspect model usage estimates by request and stage.",
  },
  {
    id: "delivery",
    name: "Delivery queue",
    group: "Operations",
    states: ["normal", "loading", "empty", "processing", "failed", "complete"],
    purpose: "Retry a notification without regenerating the report.",
  },
];
export const stateLabel = (state: string) =>
  ({
    normal: "Default",
    review: "Awaiting analyst review",
    reassessed: "After RFP reassessment",
    error: "Failed / recovery",
    partial: "Partial / missing evidence",
    complete: "Complete",
    stale: "Changed / needs review",
    unavailable: "Unavailable / access denied",
    conflict: "Conflicting evidence",
  })[state] || state.charAt(0).toUpperCase() + state.slice(1);
export const opportunities = [
  {
    title: "Digital service transformation",
    agency: "Harbour Regional Council",
    region: "Auckland",
    close: "24 Sep 2026",
    type: "Open tender",
    tag: "Deadline extended",
    sector: "Digital advisory",
  },
  {
    title: "Customer experience research",
    agency: "Southern Services Agency",
    region: "Wellington",
    close: "30 Sep 2026",
    type: "Open tender",
    tag: "New this week",
    sector: "Research",
  },
  {
    title: "Data governance advisory",
    agency: "North Coast Council",
    region: "Auckland",
    close: "6 Oct 2026",
    type: "Open tender",
    tag: "Analysis pending",
    sector: "Digital advisory",
  },
  {
    title: "Programme assurance panel",
    agency: "Central Infrastructure Office",
    region: "Nationwide",
    close: "12 Oct 2026",
    type: "Open tender",
    tag: "Relevant experience",
    sector: "Assurance",
  },
  {
    title: "Service design panel",
    agency: "Southern Services Agency",
    region: "Nationwide",
    close: "Q4 2026 · indicative",
    type: "Future opportunity",
    tag: "Planning signal",
    sector: "Digital advisory",
  },
];
export const requirements = [
  {
    id: "security",
    title: "Provide current information-security certification.",
    short: "Information security",
    page: 12,
    section: "4.2 Information security",
    detail:
      "The supplier must provide evidence of current information-security certification with its response.",
    firm: "No current certificate supplied.",
  },
  {
    id: "insurance",
    title: "Maintain professional indemnity insurance.",
    short: "Professional indemnity",
    page: 14,
    section: "4.4 Insurance",
    detail:
      "The supplier must maintain professional indemnity insurance for the term of the contract.",
    firm: "Current insurance schedule supplied.",
  },
  {
    id: "references",
    title: "Provide two comparable delivery references.",
    short: "Relevant experience",
    page: 16,
    section: "5.1 Delivery references",
    detail:
      "Provide two examples of comparable service transformation programmes completed within the last three years.",
    firm: "Two delivery references recorded in your firm profile.",
  },
];
export const sources = [
  {
    name: "Tender requirements.pdf",
    kind: "Firm upload",
    scope: "Private",
    version: 2,
    pages: 18,
    read: 16,
    checked: "9 Sep, 08:42",
    status: "2 pages need review",
  },
  {
    name: "GETS notice · digital transformation",
    kind: "Public notice",
    scope: "Public",
    version: 3,
    pages: 1,
    read: 1,
    checked: "9 Sep, 08:15",
    status: "Current",
  },
  {
    name: "Koru capability statement.pdf",
    kind: "Firm upload",
    scope: "Private",
    version: 1,
    pages: 8,
    read: 8,
    checked: "8 Sep, 16:20",
    status: "Current",
  },
  {
    name: "Agency procurement plan",
    kind: "Agency publication",
    scope: "Public",
    version: 2,
    pages: 24,
    read: 24,
    checked: "8 Sep, 11:30",
    status: "Current",
  },
];
